# Generated by Django 3.2.16 on 2022-11-08 19:20

from django.db import migrations, models
import useful_variables


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='address',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(default=1, max_length=10, validators=[useful_variables.phone]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default=None, max_length=40),
        ),
    ]
