# Generated by Django 3.2.16 on 2022-11-09 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(choices=[('insufficient', 'insufficient'), ('sufficient', 'sufficient'), ('good', 'good'), ('verygood', 'verygood'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=12),
        ),
    ]
