# Generated by Django 3.2.16 on 2022-11-08 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
