# Generated by Django 3.2.16 on 2022-11-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='parent_type',
            field=models.CharField(choices=[('0', 'Mother'), ('1', 'Father'), ('2', 'Grandmother'), ('3', 'Grandfather')], default='0', max_length=11),
        ),
    ]
