# Generated by Django 3.2.16 on 2022-11-08 22:02

from django.db import migrations, models
import useful_variables


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20221108_2120'),
        ('parent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='phone',
        ),
        migrations.AddField(
            model_name='parent',
            name='cnp',
            field=models.ManyToManyField(to='student.Student'),
        ),
        migrations.AddField(
            model_name='parent',
            name='parent_type',
            field=models.CharField(choices=[('Mother', 'Mother'), ('Father', 'Father'), ('Grandmother', 'Grandmother'), ('Grandfather', 'Grandfather')], default=None, max_length=11),
        ),
        migrations.AddField(
            model_name='parent',
            name='phone_number',
            field=models.CharField(default=None, max_length=10, validators=[useful_variables.phone]),
        ),
        migrations.AlterField(
            model_name='parent',
            name='email',
            field=models.CharField(max_length=30),
        ),
    ]
