# Generated by Django 3.2.16 on 2022-11-02 22:52

from django.db import migrations, models
import parent.models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0002_parent_parent_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.AlterField(
            model_name='parent',
            name='email',
            field=models.CharField(max_length=30, validators=[parent.models.phone]),
        ),
        migrations.AlterField(
            model_name='parent',
            name='parent_type',
            field=models.CharField(choices=[('Mother', 'Mother'), ('Father', 'Father'), ('Grandmother', 'Grandmother'), ('Grandfather', 'Grandfather')], max_length=11),
        ),
    ]
