# Generated by Django 3.2.16 on 2022-11-03 18:22

from django.db import migrations, models
import parent.models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0003_auto_20221103_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone_number',
            field=models.IntegerField(max_length=10, validators=[parent.models.phone]),
        ),
    ]
