# Generated by Django 3.2.16 on 2022-11-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0003_alter_parent_parent_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='parent_type',
            field=models.CharField(choices=[('Mother', 'Mother'), ('Father', 'Father'), ('Grandmother', 'Grandmother'), ('Grandfather', 'Grandfather')], max_length=11),
        ),
    ]
