# Generated by Django 3.2.16 on 2022-11-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20221108_2120'),
        ('parent', '0004_alter_parent_parent_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='student',
            field=models.ManyToManyField(related_name='parent_student', to='student.Student'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='cnp',
            field=models.ManyToManyField(related_name='student_cnp', to='student.Student'),
        ),
    ]
