# Generated by Django 3.2.16 on 2022-11-03 18:23

from django.db import migrations, models
import parent.models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0004_auto_20221103_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[parent.models.phone]),
        ),
    ]
