# Generated by Django 3.2.16 on 2022-11-10 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20221108_2120'),
        ('parent', '0006_auto_20221110_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='cnp',
        ),
        migrations.AddField(
            model_name='parent',
            name='cnp',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='student_cnp', to='student.student'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_student', to='student.student'),
        ),
    ]
