# Generated by Django 3.2.16 on 2022-11-13 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userextend', '0005_auto_20221113_1646'),
        ('parent', '0007_auto_20221110_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='user_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userextend.usertype'),
        ),
    ]
