# Generated by Django 3.2.16 on 2022-11-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userextend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='account_type',
            field=models.CharField(choices=[('Parent', 'Parent'), ('Teacher', 'Teacher')], default='Parent', max_length=7),
        ),
    ]
