# Generated by Django 3.2.16 on 2022-11-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollment',
            field=models.CharField(choices=[('Preparatory class', 'Preparatory class'), ('1st grade', '1st grade'), ('2nd grade', '2nd grade'), ('3rd grade', '3rd grade'), ('4th grade', '4th grade'), ('5th grade', '5th grade'), ('6th grade', '6th grade'), ('7th grade', '7th grade'), ('8th grade', '8th grade')], max_length=17),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=8),
        ),
    ]
