# Generated by Django 3.2.16 on 2022-11-08 19:20

from django.db import migrations, models
import useful_variables


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20221103_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='CNP',
            field=models.CharField(max_length=13, primary_key=True, serialize=False, validators=[useful_variables.cnp]),
        ),
    ]
